### ISSUE TITLE
Run instructions?

### ISSUE THREAD

**Issue by lawl** [Skytanic/Clarity#1]
I'my trying to get this to run. I assume the file to run is claritygui.py. I'm not a python guy so I might miss the obvious.

```
Traceback (most recent call last):
  File "claritygui.py", line 4, in <module>
    import clarity.src.handler as clarityhandler
ImportError: No module named 'clarity'
```
so I cd into the src folder and tried to patch the file:

```
diff --git a/src/claritygui.py b/src/claritygui.py
index 6d73c06..e7b9e8c 100644
--- a/src/claritygui.py
+++ b/src/claritygui.py
@@ -1,8 +1,8 @@
 #!/usr/bin/env python
 # -*- coding: utf-8 -*-
 
-import clarity.src.handler as clarityhandler
-from clarity.src.claritystyles import get_style
+import handler as clarityhandler
+from claritystyles import get_style
 import sys
 from PySide import QtGui, QtCore
 from abc import ABCMeta, abstractmethod

```
Then it works in python3 if I run it from the src folder. What is the proper way to run this?

**Comment by Skytanic** [comment]
Hi Lawl, this is actually a problem on my end, thanks for pointing it out. Basically I use the IDE PyCharm for python and my project was opened in the Project folder when it should have been opened in the src folder. Your code is correct for running it. Thanks for your question!
